version: '3'
services:

  mongo:
    image: mongo:4.4.16-rc0-focal
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE_NAME}
    ports:
      - ${MONGO_DATABASE_PORT}:27017
    volumes:
      - mongoVolume:/data/db
    networks:
      - TuniTroncNetwork

  keycloak:
    image: jboss/keycloak:10.0.0
    ports:
      - ${KEYCLOAK_PORT}:8080
    volumes:
      - keyCloak:/opt/jboss/keycloak/standalone/data
    networks:
      - TuniTroncNetwork

  tunitronc:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      MONGO_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_DATABASE_NAME: ${MONGO_DATABASE_NAME}
    depends_on:
      - mongo
    ports:
      - "${APP_PORT}:8080"
      - "${DEBUG_PORT}:8787"
    networks:
      - TuniTroncNetwork

volumes:
  mongoVolume:
  keyCloak:

networks:
  TuniTroncNetwork:
     driver: bridge